### ISSUE TITLE
Нейминг

### ISSUE THREAD

**Issue by Red-Cat-Fat** [AsmoWriter/BoomClicker#1]
https://github.com/AsmoWriter/BoomClicker/blob/3bf44b4f80b2093693a1cce36b97cd4fc6e5eaf3/Assets/Scripts/BombGrow.cs#L5-L8
### Отступы
Только TAB. Пробелам смерть!
### Имена

- Переменные внутри функции - с маленькой буквы camelCase (int someVar = 0;)
- Поле класса private/internal - с подчеркивания, _camelCase (private int _someVar;)
- Поле класса protected/public - с большой буквы, CamelCase (public int SomeVar;)
- Имена файлов, классов и неймспейсов - с большой буквы, CamelCase (EditorUtils.GUIWindow)
- Для свойств и событий - аналогично полям.
- Имя события не должно содержать On, должно заканчиваться на Event (public event System.Action ItemClickEvent;)
- Имя метода, отлавливающего событие должно содержать On, иметь совершённую форму и не должно заканчиваться на Event (private void OnItemClicked())
- Все имена функций - с большой буквы, CamelCase (private void SomeFunc())

### Общее

- Все поля, функции, свойства и события должны быть с явным модификатором (private/public/protected/internal)
- Для всех классов должен быть указан неймспейс
- Неймспейс определяется путем к скрипту, например скрипт в Assets/Scripts/Game/UI должен иметь неймспейс Game.UI, а скрипт в Assets/Scripts/Common/UI - неймспейс Common.UI
- Нельзя создавать неймспейс с именем используемых класса (Editor.Utils)
- {} скобки - на новой строке
- Не стоит пренебрегать {} для однострочных циклов и условий - меньше багов будет и проще потом править
- Unity создает по дефолту файлы с функциями Start и Update - обязательно удаляйте их если не используете

**Comment by AsmoWriter** [comment]
https://github.com/AsmoWriter/BoomClicker/commit/faac4bb680d2a5c408e0adb4fa254aa727a6f446
По возможности поправлено

**Comment by Red-Cat-Fat** [comment]
Зачем ты закрыл ишуу?

**Comment by AsmoWriter** [comment]
Я думал, что после поправки надо закрывать их.
вс, 15 мар. 2020 г., 13:07 Boronnikov Andrey <notifications@github.com>:
