### ISSUE TITLE
Не двигай спавнер

### ISSUE THREAD

**Issue by Red-Cat-Fat** [AsmoWriter/BoomClicker#2]
https://github.com/AsmoWriter/BoomClicker/blob/3bf44b4f80b2093693a1cce36b97cd4fc6e5eaf3/Assets/Scripts/RandomSpawnPosition.cs#L17
Двигать спавнер - неправильно. Если хочешь случайным образом спавнить объекты - указывай в Instance координаты спавна

**Comment by AsmoWriter** [comment]
https://github.com/AsmoWriter/BoomClicker/commit/099c7fed6cabbd75c5ad1319468c463bdf2cf19f
Исправлено
