### ISSUE TITLE
Игра не проходит дальше первой сцены. Ошибка загрузки уровня

### ISSUE THREAD

**Issue by Red-Cat-Fat** [AsmoWriter/BoomClicker#3]
![image](https://user-images.githubusercontent.com/28541280/76330042-62619900-62fe-11ea-84d8-ceca63d969e1.png)
Для корректной работы нужно было указать уровни в BuildSettings

**Comment by AsmoWriter** [comment]
https://github.com/AsmoWriter/BoomClicker/commit/78b8f2054c094b64a4fa6baa2bbf39f5ef161829
Сцены включены в настройки билда
![image](https://user-images.githubusercontent.com/61447831/76457306-9960a900-63e9-11ea-854b-31d646a5a653.png)
