### ISSUE TITLE
Переиспользуй компоненты

### ISSUE THREAD

**Issue by Red-Cat-Fat** [AsmoWriter/BoomClicker#4]
Какие отличия у ScoreCounterScriptableObject от HPCounterScriptableObject?
По факту их нет.
AddValue(-x) уменьшит тот же Counter на х.
А Action обновления имеет одинаковую сигнатуру.
По факту - это один и тот же компонент.

**Comment by AsmoWriter** [comment]
https://github.com/AsmoWriter/BoomClicker/commit/4a7214b8fc95b0d3dd63a15ee70335e327a72c8e
Переработано
