### ISSUE TITLE
Добавить, но удалить

### ISSUE THREAD

**Issue by Red-Cat-Fat** [AsmoWriter/BoomClicker#5]
https://github.com/AsmoWriter/BoomClicker/blob/3bf44b4f80b2093693a1cce36b97cd4fc6e5eaf3/Assets/Scripts/HPCounterScriptableObject.cs#L28-L32
Метод называется Add, но ты уменьшаешь значение

**Comment by AsmoWriter** [comment]
https://github.com/AsmoWriter/BoomClicker/commit/4a7214b8fc95b0d3dd63a15ee70335e327a72c8e
Переработано
