### ISSUE TITLE
Скрипты недозагрущились

### ISSUE THREAD

**Issue by Red-Cat-Fat** [AsmoWriter/BoomClicker#6]
![image](https://user-images.githubusercontent.com/28541280/76331091-b8830c00-62ff-11ea-9a50-659b2d312536.png)
Полоска хп не меняется

**Comment by AsmoWriter** [comment]
https://github.com/AsmoWriter/BoomClicker/commit/4a7214b8fc95b0d3dd63a15ee70335e327a72c8e
Доработано
